import { COLLECTION_NAMES } from "../../database/collectionNames.js";

export const REQUESTS_COLLECTION = COLLECTION_NAMES.REQUESTS;

export const JOURNEY_PERIODS_COLLECTION =
  COLLECTION_NAMES.REQUEST_JOURNEY_PERIODS;

export const SPECIFICATION_COLLECTION = COLLECTION_NAMES.REQUEST_SPECIFICATIONS;

export const NOTES_COLLECTION = COLLECTION_NAMES.REQUEST_NOTES;

export const TASKS_COLLECTION = COLLECTION_NAMES.REQUEST_TASKS;

export const TASK_NOTES_COLLECTION = COLLECTION_NAMES.REQUEST_TASK_NOTES;

export const LIST_RANK_STEP = 1000;
