import { bindTool } from "../../bindTool.js";
import type { ToolDefinition, ToolHandler } from "../../contracts.js";
import { catalogTools as definitions } from "./schemas.js";
import {
  createApplication,
  createComponent,
  createDeployment,
  createIntegration,
  createRepository,
  createRuntime,
  createServer,
  getApplication,
  getApplicationContext,
  getComponent,
  getDeployment,
  getIntegration,
  getRepository,
  getRuntime,
  getServer,
  getWorkspace,
  listApplications,
  listComponents,
  listDeployments,
  listIntegrations,
  listRepositories,
  listRuntimes,
  listServers,
  listWorkspaces,
  recordDeploymentPublication,
  updateApplication,
  updateComponent,
  updateDeployment,
  updateIntegration,
  updateRepository,
  updateRuntime,
  updateServer,
} from "./service.js";
const handlers: Record<string, ToolHandler> = {
  workspaces_list: bindTool("workspaces_list", listWorkspaces),
  workspaces_get: bindTool("workspaces_get", getWorkspace),
  applications_list: bindTool("applications_list", listApplications),
  applications_get: bindTool("applications_get", getApplication),
  applications_get_context: bindTool(
    "applications_get_context",
    getApplicationContext,
  ),
  components_list: bindTool("components_list", listComponents),
  components_get: bindTool("components_get", getComponent),
  integrations_list: bindTool("integrations_list", listIntegrations),
  integrations_get: bindTool("integrations_get", getIntegration),
  repositories_list: bindTool("repositories_list", listRepositories),
  repositories_get: bindTool("repositories_get", getRepository),
  servers_list: bindTool("servers_list", listServers),
  servers_get: bindTool("servers_get", getServer),
  deployments_list: bindTool("deployments_list", listDeployments),
  deployments_get: bindTool("deployments_get", getDeployment),
  runtimes_list: bindTool("runtimes_list", listRuntimes),
  runtimes_get: bindTool("runtimes_get", getRuntime),
  applications_create: bindTool("applications_create", createApplication),
  applications_update: bindTool("applications_update", updateApplication),
  components_create: bindTool("components_create", createComponent),
  components_update: bindTool("components_update", updateComponent),
  integrations_create: bindTool("integrations_create", createIntegration),
  integrations_update: bindTool("integrations_update", updateIntegration),
  repositories_create: bindTool("repositories_create", createRepository),
  repositories_update: bindTool("repositories_update", updateRepository),
  servers_create: bindTool("servers_create", createServer),
  servers_update: bindTool("servers_update", updateServer),
  deployments_create: bindTool("deployments_create", createDeployment),
  deployments_update: bindTool("deployments_update", updateDeployment),
  deployments_record_publication: bindTool(
    "deployments_record_publication",
    recordDeploymentPublication,
  ),
  runtimes_create: bindTool("runtimes_create", createRuntime),
  runtimes_update: bindTool("runtimes_update", updateRuntime),
};
export const catalogTools: (ToolDefinition & { handler: ToolHandler })[] =
  definitions.map((tool) => ({ ...tool, handler: handlers[tool.name] }));
