import { Router } from "express";
import { registerListSecrets } from "./listSecrets.js";
import { registerCreateRegistration } from "./createRegistration.js";
import { registerCreateSecret } from "./createSecret.js";
import { registerCreateFile } from "./createFile.js";
import { registerGetSecret } from "./getSecret.js";
import { registerUpdateCollection } from "./collection/updateCollection.js";
import { registerUpdateSecret } from "./updateSecret.js";
import { registerReplaceValue } from "./value/replaceValue.js";
import { registerReplaceFile } from "./file/replaceFile.js";
import { registerCreateReveal } from "./reveal/createReveal.js";
import { registerCreateCopy } from "./copy/createCopy.js";
import { registerCreateDownload } from "./download/createDownload.js";
import { registerCreateArchive } from "./archive/createArchive.js";
import { registerCreateRestore } from "./restore/createRestore.js";
import { registerDeletePermanent } from "./permanent/deletePermanent.js";

export const secretsRouter = Router();
registerListSecrets(secretsRouter);
registerCreateRegistration(secretsRouter);
registerCreateSecret(secretsRouter);
registerCreateFile(secretsRouter);
registerGetSecret(secretsRouter);
registerUpdateCollection(secretsRouter);
registerUpdateSecret(secretsRouter);
registerReplaceValue(secretsRouter);
registerReplaceFile(secretsRouter);
registerCreateReveal(secretsRouter);
registerCreateCopy(secretsRouter);
registerCreateDownload(secretsRouter);
registerCreateArchive(secretsRouter);
registerCreateRestore(secretsRouter);
registerDeletePermanent(secretsRouter);
