import { Router } from "express";
import { registerListDeploymentsPublications } from "./deployments/listDeploymentsPublications.js";
import { registerListApplicationsContext } from "./applications/listApplicationsContext.js";
import { registerListApplicationsComponents } from "./applications/listApplicationsComponents.js";
import { registerCreateApplicationsComponent } from "./applications/createApplicationsComponent.js";
import { registerGetComponent } from "./components/getComponent.js";
import { registerUpdateComponent } from "./components/updateComponent.js";
import { registerUpdateComponentsArchive } from "./components/updateComponentsArchive.js";
import { registerListApplicationsIntegrations } from "./applications/listApplicationsIntegrations.js";
import { registerCreateApplicationsIntegration } from "./applications/createApplicationsIntegration.js";
import { registerGetIntegration } from "./integrations/getIntegration.js";
import { registerUpdateIntegration } from "./integrations/updateIntegration.js";
import { registerUpdateIntegrationsArchive } from "./integrations/updateIntegrationsArchive.js";
import { registerListApplicationsRepositories } from "./applications/listApplicationsRepositories.js";
import { registerCreateApplicationsRepository } from "./applications/createApplicationsRepository.js";
import { registerGetRepository } from "./repositories/getRepository.js";
import { registerListRepositoriesComponents } from "./repositories/listRepositoriesComponents.js";
import { registerUpdateRepository } from "./repositories/updateRepository.js";
import { registerUpdateRepositoriesArchive } from "./repositories/updateRepositoriesArchive.js";
import { registerListWorkspacesServers } from "./workspaces/listWorkspacesServers.js";
import { registerCreateWorkspacesServer } from "./workspaces/createWorkspacesServer.js";
import { registerGetServer } from "./servers/getServer.js";
import { registerListServersRuntimes } from "./servers/listServersRuntimes.js";
import { registerListServersDeployments } from "./servers/listServersDeployments.js";
import { registerUpdateServersCollection } from "./servers/updateServersCollection.js";
import { registerUpdateServer } from "./servers/updateServer.js";
import { registerUpdateServersArchive } from "./servers/updateServersArchive.js";
import { registerUpdateServersRestore } from "./servers/updateServersRestore.js";
import { registerDeleteServersPermanent } from "./servers/deleteServersPermanent.js";
import { registerListApplicationsDeployments } from "./applications/listApplicationsDeployments.js";
import { registerCreateApplicationsDeployment } from "./applications/createApplicationsDeployment.js";
import { registerGetDeployment } from "./deployments/getDeployment.js";
import { registerUpdateDeployment } from "./deployments/updateDeployment.js";
import { registerCreateDeploymentsPublication } from "./deployments/createDeploymentsPublication.js";
import { registerUpdateDeploymentsArchive } from "./deployments/updateDeploymentsArchive.js";
import { registerListDeploymentsRuntimes } from "./deployments/listDeploymentsRuntimes.js";
import { registerCreateDeploymentsRuntime } from "./deployments/createDeploymentsRuntime.js";
import { registerGetRuntime } from "./runtimes/getRuntime.js";
import { registerUpdateRuntime } from "./runtimes/updateRuntime.js";
import { registerUpdateRuntimesArchive } from "./runtimes/updateRuntimesArchive.js";
import { registerListApplicationsTopologyDiagrams } from "./applications/listApplicationsTopologyDiagrams.js";
import { registerCreateApplicationsTopologyDiagram } from "./applications/createApplicationsTopologyDiagram.js";
import { registerGetTopologyDiagram } from "./topology-diagrams/getTopologyDiagram.js";
import { registerUpdateTopologyDiagram } from "./topology-diagrams/updateTopologyDiagram.js";
import { registerUpdateComponentsRestore } from "./components/updateComponentsRestore.js";
import { registerDeleteComponentsPermanent } from "./components/deleteComponentsPermanent.js";
import { registerUpdateIntegrationsRestore } from "./integrations/updateIntegrationsRestore.js";
import { registerDeleteIntegrationsPermanent } from "./integrations/deleteIntegrationsPermanent.js";
import { registerUpdateRepositoriesRestore } from "./repositories/updateRepositoriesRestore.js";
import { registerDeleteRepositoriesPermanent } from "./repositories/deleteRepositoriesPermanent.js";
import { registerUpdateDeploymentsRestore } from "./deployments/updateDeploymentsRestore.js";
import { registerDeleteDeploymentsPermanent } from "./deployments/deleteDeploymentsPermanent.js";
import { registerUpdateRuntimesRestore } from "./runtimes/updateRuntimesRestore.js";
import { registerDeleteRuntimesPermanent } from "./runtimes/deleteRuntimesPermanent.js";

export const catalogTopologyRouter = Router();
registerListDeploymentsPublications(catalogTopologyRouter);
registerListApplicationsContext(catalogTopologyRouter);
registerListApplicationsComponents(catalogTopologyRouter);
registerCreateApplicationsComponent(catalogTopologyRouter);
registerGetComponent(catalogTopologyRouter);
registerUpdateComponent(catalogTopologyRouter);
registerUpdateComponentsArchive(catalogTopologyRouter);
registerListApplicationsIntegrations(catalogTopologyRouter);
registerCreateApplicationsIntegration(catalogTopologyRouter);
registerGetIntegration(catalogTopologyRouter);
registerUpdateIntegration(catalogTopologyRouter);
registerUpdateIntegrationsArchive(catalogTopologyRouter);
registerListApplicationsRepositories(catalogTopologyRouter);
registerCreateApplicationsRepository(catalogTopologyRouter);
registerGetRepository(catalogTopologyRouter);
registerListRepositoriesComponents(catalogTopologyRouter);
registerUpdateRepository(catalogTopologyRouter);
registerUpdateRepositoriesArchive(catalogTopologyRouter);
registerListWorkspacesServers(catalogTopologyRouter);
registerCreateWorkspacesServer(catalogTopologyRouter);
registerGetServer(catalogTopologyRouter);
registerListServersRuntimes(catalogTopologyRouter);
registerListServersDeployments(catalogTopologyRouter);
registerUpdateServersCollection(catalogTopologyRouter);
registerUpdateServer(catalogTopologyRouter);
registerUpdateServersArchive(catalogTopologyRouter);
registerUpdateServersRestore(catalogTopologyRouter);
registerDeleteServersPermanent(catalogTopologyRouter);
registerListApplicationsDeployments(catalogTopologyRouter);
registerCreateApplicationsDeployment(catalogTopologyRouter);
registerGetDeployment(catalogTopologyRouter);
registerUpdateDeployment(catalogTopologyRouter);
registerCreateDeploymentsPublication(catalogTopologyRouter);
registerUpdateDeploymentsArchive(catalogTopologyRouter);
registerListDeploymentsRuntimes(catalogTopologyRouter);
registerCreateDeploymentsRuntime(catalogTopologyRouter);
registerGetRuntime(catalogTopologyRouter);
registerUpdateRuntime(catalogTopologyRouter);
registerUpdateRuntimesArchive(catalogTopologyRouter);
registerListApplicationsTopologyDiagrams(catalogTopologyRouter);
registerCreateApplicationsTopologyDiagram(catalogTopologyRouter);
registerGetTopologyDiagram(catalogTopologyRouter);
registerUpdateTopologyDiagram(catalogTopologyRouter);
registerUpdateComponentsRestore(catalogTopologyRouter);
registerDeleteComponentsPermanent(catalogTopologyRouter);
registerUpdateIntegrationsRestore(catalogTopologyRouter);
registerDeleteIntegrationsPermanent(catalogTopologyRouter);
registerUpdateRepositoriesRestore(catalogTopologyRouter);
registerDeleteRepositoriesPermanent(catalogTopologyRouter);
registerUpdateDeploymentsRestore(catalogTopologyRouter);
registerDeleteDeploymentsPermanent(catalogTopologyRouter);
registerUpdateRuntimesRestore(catalogTopologyRouter);
registerDeleteRuntimesPermanent(catalogTopologyRouter);
