import { Router } from "express";
import { registerListDocumentTypes } from "./listDocumentTypes.js";
import { registerListDocuments } from "./listDocuments.js";
import { registerCreateDocument } from "./createDocument.js";
import { registerCreateDocumentsAttachment } from "./documents/createDocumentsAttachment.js";
import { registerGetDocumentsAttachment } from "./documents/getDocumentsAttachment.js";
import { registerDeleteDocumentsAttachment } from "./documents/deleteDocumentsAttachment.js";
import { registerUpdateDocumentsAttachmentsTags } from "./documents/attachments/updateDocumentsAttachmentsTags.js";
import { registerCreateDocumentsReplicate } from "./documents/createDocumentsReplicate.js";
import { registerListDocumentsRevisions } from "./documents/listDocumentsRevisions.js";
import { registerListDocumentsObservations } from "./documents/listDocumentsObservations.js";
import { registerCreateDocumentsObservation } from "./documents/createDocumentsObservation.js";
import { registerUpdateDocumentsCollection } from "./documents/updateDocumentsCollection.js";
import { registerGetDocument } from "./documents/getDocument.js";
import { registerReplaceDocument } from "./documents/replaceDocument.js";
import { registerDeleteDocumentsPermanent } from "./documents/deleteDocumentsPermanent.js";
import { registerUpdateDocumentsRestore } from "./documents/updateDocumentsRestore.js";
import { registerDeleteDocument } from "./documents/deleteDocument.js";
import { registerListDocumentsContent } from "./documents/listDocumentsContent.js";
import { registerListDocumentsReferences } from "./documents/listDocumentsReferences.js";
import { registerGetDocumentsRevision } from "./documents/getDocumentsRevision.js";
import { registerGetDocumentsObservation } from "./documents/getDocumentsObservation.js";
import { registerListDocumentsAttachments } from "./documents/listDocumentsAttachments.js";
import { registerListDocumentsAttachmentsMetadata } from "./documents/attachments/listDocumentsAttachmentsMetadata.js";

export const knowledgeRecordsRouter = Router();
registerListDocumentTypes(knowledgeRecordsRouter);
registerListDocuments(knowledgeRecordsRouter);
registerCreateDocument(knowledgeRecordsRouter);
registerCreateDocumentsAttachment(knowledgeRecordsRouter);
registerGetDocumentsAttachment(knowledgeRecordsRouter);
registerDeleteDocumentsAttachment(knowledgeRecordsRouter);
registerUpdateDocumentsAttachmentsTags(knowledgeRecordsRouter);
registerCreateDocumentsReplicate(knowledgeRecordsRouter);
registerListDocumentsRevisions(knowledgeRecordsRouter);
registerListDocumentsObservations(knowledgeRecordsRouter);
registerCreateDocumentsObservation(knowledgeRecordsRouter);
registerUpdateDocumentsCollection(knowledgeRecordsRouter);
registerGetDocument(knowledgeRecordsRouter);
registerReplaceDocument(knowledgeRecordsRouter);
registerDeleteDocumentsPermanent(knowledgeRecordsRouter);
registerUpdateDocumentsRestore(knowledgeRecordsRouter);
registerDeleteDocument(knowledgeRecordsRouter);
registerListDocumentsContent(knowledgeRecordsRouter);
registerListDocumentsReferences(knowledgeRecordsRouter);
registerGetDocumentsRevision(knowledgeRecordsRouter);
registerGetDocumentsObservation(knowledgeRecordsRouter);
registerListDocumentsAttachments(knowledgeRecordsRouter);
registerListDocumentsAttachmentsMetadata(knowledgeRecordsRouter);
