import { Router } from "express";
import { registerListRequests } from "./listRequests.js";
import { registerListCollectionItems } from "./listCollectionItems.js";
import { registerGetRequest } from "./getRequest.js";
import { registerCreateRequest } from "./createRequest.js";
import { registerCreateAttachment } from "./attachments/createAttachment.js";
import { registerGetAttachment } from "./attachments/getAttachment.js";
import { registerDeleteAttachment } from "./attachments/deleteAttachment.js";
import { registerUpdateAttachmentsTags } from "./attachments/updateAttachmentsTags.js";
import { registerReplaceRequest } from "./replaceRequest.js";
import { registerUpdateOrder } from "./order/updateOrder.js";
import { registerUpdateCollection } from "./collection/updateCollection.js";
import { registerCreateNote } from "./notes/createNote.js";
import { registerReplaceNote } from "./notes/replaceNote.js";
import { registerDeleteNote } from "./notes/deleteNote.js";
import { registerCreateTask } from "./tasks/createTask.js";
import { registerReplaceTask } from "./tasks/replaceTask.js";
import { registerDeleteTask } from "./tasks/deleteTask.js";
import { registerCreateTasksNote } from "./tasks/createTasksNote.js";
import { registerReplaceTasksNote } from "./tasks/replaceTasksNote.js";
import { registerDeleteTasksNote } from "./tasks/deleteTasksNote.js";
import { registerDeleteRequest } from "./deleteRequest.js";
import { registerListSpecification } from "./specification/listSpecification.js";
import { registerGetSpecificationSection } from "./specification/getSpecificationSection.js";
import { registerListChecklist } from "./checklist/listChecklist.js";
import { registerListJourneys } from "./journeys/listJourneys.js";
import { registerListNotes } from "./notes/listNotes.js";
import { registerGetNote } from "./notes/getNote.js";
import { registerListTasks } from "./tasks/listTasks.js";
import { registerGetTask } from "./tasks/getTask.js";
import { registerListTasksNotes } from "./tasks/listTasksNotes.js";
import { registerGetTasksNote } from "./tasks/getTasksNote.js";
import { registerListImplementationContext } from "./implementation-context/listImplementationContext.js";
import { registerListAttachments } from "./attachments/listAttachments.js";
import { registerListAttachmentsMetadata } from "./attachments/listAttachmentsMetadata.js";
import { registerListTasksAttachments } from "./tasks/listTasksAttachments.js";
import { registerListTasksAttachmentsMetadata } from "./tasks/attachments/listTasksAttachmentsMetadata.js";
import { registerGetTasksAttachment } from "./tasks/getTasksAttachment.js";
import { registerCreateTasksAttachment } from "./tasks/createTasksAttachment.js";
import { registerUpdateTasksAttachmentsTags } from "./tasks/attachments/updateTasksAttachmentsTags.js";
import { registerDeleteTasksAttachment } from "./tasks/deleteTasksAttachment.js";

export const requestsRouter = Router();
registerListRequests(requestsRouter);
registerListCollectionItems(requestsRouter);
registerGetRequest(requestsRouter);
registerCreateRequest(requestsRouter);
registerCreateAttachment(requestsRouter);
registerGetAttachment(requestsRouter);
registerDeleteAttachment(requestsRouter);
registerUpdateAttachmentsTags(requestsRouter);
registerReplaceRequest(requestsRouter);
registerUpdateOrder(requestsRouter);
registerUpdateCollection(requestsRouter);
registerCreateNote(requestsRouter);
registerReplaceNote(requestsRouter);
registerDeleteNote(requestsRouter);
registerCreateTask(requestsRouter);
registerReplaceTask(requestsRouter);
registerDeleteTask(requestsRouter);
registerCreateTasksNote(requestsRouter);
registerReplaceTasksNote(requestsRouter);
registerDeleteTasksNote(requestsRouter);
registerDeleteRequest(requestsRouter);
registerListSpecification(requestsRouter);
registerGetSpecificationSection(requestsRouter);
registerListChecklist(requestsRouter);
registerListJourneys(requestsRouter);
registerListNotes(requestsRouter);
registerGetNote(requestsRouter);
registerListTasks(requestsRouter);
registerGetTask(requestsRouter);
registerListTasksNotes(requestsRouter);
registerGetTasksNote(requestsRouter);
registerListImplementationContext(requestsRouter);
registerListAttachments(requestsRouter);
registerListAttachmentsMetadata(requestsRouter);
registerListTasksAttachments(requestsRouter);
registerListTasksAttachmentsMetadata(requestsRouter);
registerGetTasksAttachment(requestsRouter);
registerCreateTasksAttachment(requestsRouter);
registerUpdateTasksAttachmentsTags(requestsRouter);
registerDeleteTasksAttachment(requestsRouter);
