import {
  archiveComponent,
  archiveDeployment,
  archiveIntegration,
  archiveRepository,
  archiveRuntime,
  createComponent,
  createDeployment,
  createIntegration,
  createRepository,
  createRuntime,
  deleteComponent,
  deleteDeployment,
  deleteIntegration,
  deleteRepository,
  deleteRuntime,
  fetchComponent,
  fetchDeployment,
  fetchIntegration,
  fetchRepository,
  fetchRuntime,
  restoreComponent,
  restoreDeployment,
  restoreIntegration,
  restoreRepository,
  restoreRuntime,
  updateComponent,
  updateDeployment,
  updateIntegration,
  updateRepository,
  updateRuntime,
} from "../../../api.js";

export const CATALOG_ENTITY_API = {
  integration: {
    create: createIntegration,
    update: updateIntegration,
    archive: archiveIntegration,
    restore: restoreIntegration,
    remove: deleteIntegration,
    detail: fetchIntegration,
    response: "integration",
  },
  component: {
    create: createComponent,
    update: updateComponent,
    archive: archiveComponent,
    restore: restoreComponent,
    remove: deleteComponent,
    detail: fetchComponent,
    response: "component",
  },
  repository: {
    create: createRepository,
    update: updateRepository,
    archive: archiveRepository,
    restore: restoreRepository,
    remove: deleteRepository,
    detail: fetchRepository,
    response: "repository",
  },
  deployment: {
    create: createDeployment,
    update: updateDeployment,
    archive: archiveDeployment,
    restore: restoreDeployment,
    remove: deleteDeployment,
    detail: fetchDeployment,
    response: "deployment",
  },
  runtime: {
    create: createRuntime,
    update: updateRuntime,
    archive: archiveRuntime,
    restore: restoreRuntime,
    remove: deleteRuntime,
    detail: fetchRuntime,
    response: "runtime",
  },
};
