import { Router } from "express";
import { registerGetRuntimesActiveMonitor } from "./runtimes/getRuntimesActiveMonitor.js";
import { registerGetRuntimeTopology } from "./getRuntimeTopology.js";
import { registerGetRuntimeTargets } from "./getRuntimeTargets.js";
import { registerListTemplates } from "./listTemplates.js";
import { registerGetMetadataProfiles } from "./getMetadataProfiles.js";
import { registerCreateTemplatesPreview } from "./templates/createTemplatesPreview.js";
import { registerCreateTemplate } from "./createTemplate.js";
import { registerGetTemplate } from "./templates/getTemplate.js";
import { registerUpdateTemplate } from "./templates/updateTemplate.js";
import { registerListTemplatesVersionsUsage } from "./templates/versions/listTemplatesVersionsUsage.js";
import { registerListTemplatesVersionsContract } from "./templates/versions/listTemplatesVersionsContract.js";
import { registerCreateTemplatesVersionsValidate } from "./templates/versions/createTemplatesVersionsValidate.js";
import { registerCreateTemplatesVersionsActivate } from "./templates/versions/createTemplatesVersionsActivate.js";
import { registerCreateTemplatesVersionsDeactivate } from "./templates/versions/createTemplatesVersionsDeactivate.js";
import { registerDeleteTemplatesVersion } from "./templates/deleteTemplatesVersion.js";
import { registerListRuntimesActiveMonitors } from "./runtimes/listRuntimesActiveMonitors.js";
import { registerCreateRuntimesActiveMonitor } from "./runtimes/createRuntimesActiveMonitor.js";
import { registerUpdateRuntimesActiveMonitor } from "./runtimes/updateRuntimesActiveMonitor.js";
import { registerDeleteRuntimesActiveMonitor } from "./runtimes/deleteRuntimesActiveMonitor.js";
import { registerCreateRuntimesActiveMonitorsExecution } from "./runtimes/active-monitors/createRuntimesActiveMonitorsExecution.js";
import { registerCreateExecutorLease } from "./executor/createExecutorLease.js";
import { registerCreateExecutorLeasesRenew } from "./executor/leases/createExecutorLeasesRenew.js";
import { registerCreateExecutorLeasesResult } from "./executor/leases/createExecutorLeasesResult.js";
import { registerCreateRuntimesManualObservation } from "./runtimes/createRuntimesManualObservation.js";
import { registerCreateRuntimesSignal } from "./runtimes/createRuntimesSignal.js";
import { registerListApplicationsHealth } from "./applications/listApplicationsHealth.js";
import { registerListRuntimesHealthSummary } from "./runtimes/listRuntimesHealthSummary.js";
import { registerListRuntimesTimeline } from "./runtimes/listRuntimesTimeline.js";
import { registerListRuntimesSignals } from "./runtimes/listRuntimesSignals.js";

export const monitoringRouter = Router();
registerGetRuntimesActiveMonitor(monitoringRouter);
registerGetRuntimeTopology(monitoringRouter);
registerGetRuntimeTargets(monitoringRouter);
registerListTemplates(monitoringRouter);
registerGetMetadataProfiles(monitoringRouter);
registerCreateTemplatesPreview(monitoringRouter);
registerCreateTemplate(monitoringRouter);
registerGetTemplate(monitoringRouter);
registerUpdateTemplate(monitoringRouter);
registerListTemplatesVersionsUsage(monitoringRouter);
registerListTemplatesVersionsContract(monitoringRouter);
registerCreateTemplatesVersionsValidate(monitoringRouter);
registerCreateTemplatesVersionsActivate(monitoringRouter);
registerCreateTemplatesVersionsDeactivate(monitoringRouter);
registerDeleteTemplatesVersion(monitoringRouter);
registerListRuntimesActiveMonitors(monitoringRouter);
registerCreateRuntimesActiveMonitor(monitoringRouter);
registerUpdateRuntimesActiveMonitor(monitoringRouter);
registerDeleteRuntimesActiveMonitor(monitoringRouter);
registerCreateRuntimesActiveMonitorsExecution(monitoringRouter);
registerCreateExecutorLease(monitoringRouter);
registerCreateExecutorLeasesRenew(monitoringRouter);
registerCreateExecutorLeasesResult(monitoringRouter);
registerCreateRuntimesManualObservation(monitoringRouter);
registerCreateRuntimesSignal(monitoringRouter);
registerListApplicationsHealth(monitoringRouter);
registerListRuntimesHealthSummary(monitoringRouter);
registerListRuntimesTimeline(monitoringRouter);
registerListRuntimesSignals(monitoringRouter);
