import { Router } from "express";
import { registerListImportsEmlSanitization } from "./imports/eml/listImportsEmlSanitization.js";
import { registerReplaceImportsEmlSanitization } from "./imports/eml/replaceImportsEmlSanitization.js";
import { registerListIssues } from "./listIssues.js";
import { registerCreateIssue } from "./createIssue.js";
import { registerCreateImportsEml } from "./imports/createImportsEml.js";
import { registerGetSummary } from "./getSummary.js";
import { registerListAggregate } from "./listAggregate.js";
import { registerGetTaxonomy } from "./getTaxonomy.js";
import { registerReplaceTaxonomy } from "./replaceTaxonomy.js";
import { registerTransferTaxonomy } from "./transferTaxonomy.js";
import { registerCreateAttachment } from "./attachments/createAttachment.js";
import { registerGetAttachment } from "./attachments/getAttachment.js";
import { registerDeleteAttachment } from "./attachments/deleteAttachment.js";
import { registerUpdateAttachmentsTags } from "./attachments/updateAttachmentsTags.js";
import { registerCreateComment } from "./comments/createComment.js";
import { registerReplaceComment } from "./comments/replaceComment.js";
import { registerDeleteComment } from "./comments/deleteComment.js";
import { registerGetByTaxonomy } from "./by-taxonomy/getByTaxonomy.js";
import { registerReplaceClassification } from "./classification/replaceClassification.js";
import { registerUpdateIssue } from "./updateIssue.js";
import { registerGetIssue } from "./getIssue.js";
import { registerListComments } from "./comments/listComments.js";
import { registerGetComment } from "./comments/getComment.js";
import { registerListClassification } from "./classification/listClassification.js";
import { registerListAttachments } from "./attachments/listAttachments.js";
import { registerListAttachmentsMetadata } from "./attachments/listAttachmentsMetadata.js";

export const issuesRouter = Router();
registerListImportsEmlSanitization(issuesRouter);
registerReplaceImportsEmlSanitization(issuesRouter);
registerListIssues(issuesRouter);
registerCreateIssue(issuesRouter);
registerCreateImportsEml(issuesRouter);
registerGetSummary(issuesRouter);
registerListAggregate(issuesRouter);
registerGetTaxonomy(issuesRouter);
registerReplaceTaxonomy(issuesRouter);
registerTransferTaxonomy(issuesRouter);
registerCreateAttachment(issuesRouter);
registerGetAttachment(issuesRouter);
registerDeleteAttachment(issuesRouter);
registerUpdateAttachmentsTags(issuesRouter);
registerCreateComment(issuesRouter);
registerReplaceComment(issuesRouter);
registerDeleteComment(issuesRouter);
registerGetByTaxonomy(issuesRouter);
registerReplaceClassification(issuesRouter);
registerUpdateIssue(issuesRouter);
registerGetIssue(issuesRouter);
registerListComments(issuesRouter);
registerGetComment(issuesRouter);
registerListClassification(issuesRouter);
registerListAttachments(issuesRouter);
registerListAttachmentsMetadata(issuesRouter);
